import "./globals.css";
import { Poppins, Zilla_Slab } from "next/font/google";
import { CartProvider } from "@/lib/cart-context";

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "700"],
  variable: "--font-poppins",
});

export const zillaSlab = Zilla_Slab({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-zilla",
});

export const metadata = {
  title: "Chip Happens ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${zillaSlab.variable} antialiased  `}
      >
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
